package com.asi.hardwareinventory;

import android.Manifest;import android.content.ContentValues;import android.content.pm.PackageManager;import android.net.Uri;import android.os.Build;import android.os.Bundle;import android.os.Environment;import android.provider.MediaStore;import android.webkit.JavascriptInterface;import android.webkit.WebResourceRequest;import android.webkit.WebResourceResponse;import android.webkit.WebSettings;import android.webkit.WebView;import android.webkit.WebViewClient;import android.widget.Toast;
import androidx.activity.OnBackPressedCallback;import androidx.annotation.NonNull;import androidx.appcompat.app.AppCompatActivity;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import androidx.webkit.WebViewAssetLoader;
import java.io.File;import java.io.FileOutputStream;import java.io.OutputStream;import java.nio.charset.StandardCharsets;

public class MainActivity extends AppCompatActivity {
 private static final int STORAGE_PERMISSION_REQUEST=201; private WebView webView; private String pendingCsv,pendingFilename;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);webView=findViewById(R.id.webView);
  WebViewAssetLoader loader=new WebViewAssetLoader.Builder().addPathHandler("/assets/",new WebViewAssetLoader.AssetsPathHandler(this)).build();
  webView.setWebViewClient(new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return loader.shouldInterceptRequest(r.getUrl());}@Override public WebResourceResponse shouldInterceptRequest(WebView v,String u){return loader.shouldInterceptRequest(Uri.parse(u));}});
  WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setBuiltInZoomControls(false);s.setSupportZoom(false);
  webView.addJavascriptInterface(new AndroidBridge(),"Android");webView.loadUrl("https://appassets.androidplatform.net/assets/www/index.html");
  getOnBackPressedDispatcher().addCallback(this,new OnBackPressedCallback(true){@Override public void handleOnBackPressed(){if(webView.canGoBack())webView.goBack();else finish();}});
 }
 public class AndroidBridge{@JavascriptInterface public void saveCsv(String c,String f){runOnUiThread(()->{if(Build.VERSION.SDK_INT<=28&&ContextCompat.checkSelfPermission(MainActivity.this,Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED){pendingCsv=c;pendingFilename=safe(f);ActivityCompat.requestPermissions(MainActivity.this,new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},STORAGE_PERMISSION_REQUEST);return;}save(c,safe(f));});}}
 private String safe(String f){String x=f==null?"hardware_inventory.csv":f.replaceAll("[\\\\/:*?\"<>|]","_");return x.toLowerCase().endsWith(".csv")?x:x+".csv";}
 private void save(String c,String f){try{OutputStream out;if(Build.VERSION.SDK_INT>=29){ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,f);v.put(MediaStore.Downloads.MIME_TYPE,"text/csv");v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/Hardware Inventory");v.put(MediaStore.Downloads.IS_PENDING,1);Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new Exception("Cannot create file");out=getContentResolver().openOutputStream(u);if(out==null)throw new Exception("Cannot open file");out.write(c.getBytes(StandardCharsets.UTF_8));out.close();v.clear();v.put(MediaStore.Downloads.IS_PENDING,0);getContentResolver().update(u,v,null,null);}else{File d=new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),"Hardware Inventory");if(!d.exists()&&!d.mkdirs())throw new Exception("Cannot create folder");out=new FileOutputStream(new File(d,f));out.write(c.getBytes(StandardCharsets.UTF_8));out.close();}Toast.makeText(this,"Saved to Downloads/Hardware Inventory/"+f,Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Export failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 @Override public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==STORAGE_PERMISSION_REQUEST){if(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED&&pendingCsv!=null)save(pendingCsv,pendingFilename);else Toast.makeText(this,"Storage permission is required for CSV export.",Toast.LENGTH_LONG).show();pendingCsv=null;pendingFilename=null;}}
 @Override protected void onDestroy(){if(webView!=null){webView.removeJavascriptInterface("Android");webView.destroy();}super.onDestroy();}
}
